### ISSUE TITLE
NPE: UrlPathHelper.removeSemicolonContent:93

### ISSUE THREAD

**Issue by markkolich** [markkolich/curacao#17]
This needs to be investigated/fixed:

```
java.lang.NullPointerException: null
	at com.kolich.curacao.util.helpers.UrlPathHelper.removeSemicolonContent(UrlPathHelper.java:93) ~[curacao-2.9-M1.jar:2.9-M1]
	at com.kolich.curacao.util.helpers.UrlPathHelper.decodeAndCleanUriString(UrlPathHelper.java:88) ~[curacao-2.9-M1.jar:2.9-M1]
	at com.kolich.curacao.util.helpers.UrlPathHelper.getRequestUri(UrlPathHelper.java:81) ~[curacao-2.9-M1.jar:2.9-M1]
	at com.kolich.curacao.util.helpers.UrlPathHelper.getPathWithinApplication(UrlPathHelper.java:58) ~[curacao-2.9-M1.jar:2.9-M1]
	at com.kolich.curacao.util.helpers.UrlPathHelper.getPathWithinApplication(UrlPathHelper.java:47) ~[curacao-2.9-M1.jar:2.9-M1]
	at com.kolich.curacao.CuracaoControllerInvoker.call(CuracaoControllerInvoker.java:69) ~[curacao-2.9-M1.jar:2.9-M1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_31]
	at com.kolich.curacao.util.MDCAwareRunnableWrapper.run(MDCAwareRunnableWrapper.java:70) [curacao-2.9-M1.jar:2.9-M1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]
```

**Comment by markkolich** [comment]
This looks like `HttpServletRequest.getRequestURI()` returned `null`.  Looking at Jetty's `HttpUri.getPathAndParam()` this seems possible to happen so perhaps we need to catch this case more gracefully.

**Comment by markkolich** [comment]
Apparently it's possible for HttpServletRequest.getRequestURI() to return null.  Looking at Jetty 9 source specifically, there is a case in which the Servlet container could return null although the servlet spec seems to imply that returning null is invalid/impossible.  I've decided not to do anything about this and just ignore the fact that the servlet container could be wrong and have bugs, and therefore, it's not Curacao's job to work around those bugs by adding null checks everywhere.
