### ISSUE TITLE
NPE: EncodedRequestBodyMapper.parse(EncodedRequestBodyMapper.java:69)

### ISSUE THREAD

**Issue by markkolich** [markkolich/curacao#20]
NPE with this request:

```
[mkolich@mbp]~$ telnet localhost 8080
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
POST /curacao/api/login HTTP/1.1
Host: localhost
Content-Length: 1

f
HTTP/1.1 500 Server Error
Date: Fri, 05 Jun 2015 04:04:33 GMT
Content-Length: 0
Server: Jetty(9.2.10.v20150310)

^]
telnet> quit
Connection closed.
```

Reproducible every time:

```
2015-06-04 21:04:35,167 WARN  [curacao-examples-9] c.k.c.h.ReturnTypeMapperCallbackHandler - Failure occurred, handling exception.
java.lang.NullPointerException: null
	at java.net.URLDecoder.decode(URLDecoder.java:136) ~[na:1.8.0_40]
	at com.kolich.curacao.mappers.request.types.body.EncodedRequestBodyMapper.parse(EncodedRequestBodyMapper.java:69) ~[curacao-3.0.jar:3.0]
	at com.kolich.curacao.mappers.request.types.body.EncodedRequestBodyMapper.resolveWithStringAndEncoding(EncodedRequestBodyMapper.java:51) ~[curacao-3.0.jar:3.0]
	at com.kolich.curacao.mappers.request.types.body.RequestBodyAsCharsetAwareStringMapper.resolveWithBody(RequestBodyAsCharsetAwareStringMapper.java:42) ~[curacao-3.0.jar:3.0]
	at com.kolich.curacao.mappers.request.types.body.MemoryBufferingRequestBodyMapper.resolve(MemoryBufferingRequestBodyMapper.java:109) ~[curacao-3.0.jar:3.0]
	at com.kolich.curacao.CuracaoControllerInvoker.buildPopulatedParameterList(CuracaoControllerInvoker.java:182) ~[curacao-3.0.jar:3.0]
	at com.kolich.curacao.CuracaoControllerInvoker.call(CuracaoControllerInvoker.java:122) ~[curacao-3.0.jar:3.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_40]
	at com.kolich.curacao.CuracaoRunnable.run(CuracaoRunnable.java:68) [curacao-3.0.jar:3.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
```

**Comment by markkolich** [comment]
Fixed in release 3.0
