### ISSUE TITLE
CuracaoReflectionUtils incorrectly matches .class files for compiled inner classes and lambdas

### ISSUE THREAD

**Issue by markkolich** [markkolich/curacao#21]
The "fix" for this issue https://github.com/markkolich/curacao/issues/8 left us with broken class matching that would incorrectly match `.class` files for anonymous inner classes and Java 8 lambdas.

This method is just wrong:

```java
private static final String getCanonicalClassFromInputFqn(final String input) {
  // Split on "$" for FQN's that look like:
  //   com.a.b.c.D$Foobar.class
  // Even if there's no "$" to split on, index zero of the resulting
  // split should just be the original input string, and never null.
  String s = input.split("\\$")[0];
  // If the the splitted string ends with ".class" remove the suffix.
  //   com.a.b.c.Foobar.class
  // So we'll be left with just com.a.b.c.Foobar as desired.
  if (s.endsWith(CLASS_EXTENSION)) {
    s = s.substring(0, s.length() - 6);
  }
  return s;
}
```

Not sure how I didn't catch this before, but this was doomed to fail.  The reason being is that the Java compiler splits out anonymous inner classes and Java 8 lambdas into their own `.class` files.  For instance, this class:

```java
public class Foo {
  // ...
  public static class Bar {
    // ...
  }
}
```

Produces these `.class` files once compiled:

* Foo.class
* Foo$Bar.class

The bug here is that if Curacao's dependency injection mechanism asks for class `Foo` the existing method `getCanonicalClassFromInputFqn` incorrectly matches `Foo$Bar` and tells `org.reflections` to pick the wrong class file.  That leads to fun exceptions like this:

```
com.kolich.curacao.exceptions.reflection.ComponentInstantiationException: Failed to instantiate component instance: Foo
	at com.kolich.curacao.components.ComponentTable.buildComponentTable(ComponentTable.java:119)
	at com.kolich.curacao.components.ComponentTable.<init>(ComponentTable.java:87)
	at com.kolich.curacao.CuracaoContextListener.contextInitialized(CuracaoContextListener.java:111)
Caused by:
java.lang.NoSuchMethodException: Foo$Bar.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)
	at com.kolich.curacao.components.ComponentTable.instantiate(ComponentTable.java:135)
	at com.kolich.curacao.components.ComponentTable.instantiate(ComponentTable.java:182)
```

**Comment by markkolich** [comment]
Resolved with commit https://github.com/markkolich/curacao/commit/e534de980c7e3c9fabb5ba4dabbde3e1796b8971

Bumping Curacao rev to 3.1 in preparation for release
